name: Send Random Quote to Webhook

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-quote-job:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Pull the repository code

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python in the environment
      with:
        python-version: '3.x'  # Use Python version 3.x

    - name: Install dependencies
      run: pip install requests supabase  # Install necessary Python packages

    - name: Run Python script
      run: python send_quote.py  # Run your script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}  # Use Supabase URL from secrets
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}  # Use Supabase API key from secrets
